#!/usr/bin/env bash

set -e

if [[ $# != 1 ]]; then
  echo "    Usage: $(basename $0) <DIRECTORY>"
  echo "    Example: $(basename $0) $HOME/code"
  echo 
  echo "Examines the git repositories in \`DIRECTORY\` and outputs all which _aren't_ starred on github."
  echo
  echo "Assumes that the repositories in \`DIRECTORY\` mimic the github \`org/repo\` pattern, as follows:"
  echo
  echo "    ~/DIRECTORY $ ls -d */*"
  echo "    daneden/animate.css"
  echo "    discourse/discourse"
  echo "    golangcookbook/golangcookbook.github.io"
  echo "    jnunemaker/nunes"
  echo "    ..."
  exit 3
fi

base_dir=$1
starred=$(jq -r '.[] | .full_name' starred.json)

cd $base_dir
locals=$(\ls -d */* | cat)

for name in $locals; do
  if ! echo "$starred" | grep -xq "$name"; then echo "$name"; fi
done



